training: !!bool "true"
device: "cuda"
unprocessed_data: './vox1/*/*/*'
---
data:
    train_path: './train_tisv'
    #train_path_unprocessed: './vox1/train/*/*/*.m4a'
    test_path: './test_tisv'
    #test_path_unprocessed: './vox2/test/*/*/*.m4a'
    data_preprocessed: !!bool "true"
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/Speaker_Verification_Vox1/model.model' #Model path for testing, inference, or resuming training
---
train:
    N : 4 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.01
    epochs: 100 #Max training speaker epoch
    log_interval: 30 #Iterations before printing progress
    log_file: './speech_id_checkpoint/Stats'
    checkpoint_interval: 20 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 2 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs

---
integration:
    verify_upload_folder: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/receiver/uploads_verification/'

    speaker_verification_path: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/Speaker_Verification_Vox1/' #path to the speaker verification model
    enroll_upload_audio_folder: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/receiver/uploads_enrollment/audio/'
    enroll_preprocessed_audio: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/receiver/enroll_preprocessed/audio/'

    face_verification_path: '/home/sahar/benchohra/DFace_production/'
    enroll_upload_photo_folder: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/receiver/uploads_enrollment/photo/'
    enroll_preprocessed_photo: '/home/sahar/Documents/Mahmoudi_Benchohra_Project/receiver/enroll_preprocessed/photo/'
